test-settings

diff --git a/.github/workflows/openwrt-ci.yml b/.github/workflows/openwrt-ci.yml
--- a/.github/workflows/openwrt-ci.yml
+++ b/.github/workflows/openwrt-ci.yml
@@ -83,7 +83,6 @@ jobs:
 
           sudo chmod +x $GITHUB_WORKSPACE/Scripts/Packages.sh
           sudo chmod +x $GITHUB_WORKSPACE/Scripts/Settings.sh
-          sudo chmod +x $GITHUB_WORKSPACE/package/jiale/init_settings/files/init_script
 
           sudo mkdir -p /mnt/build_wrt
           sudo chown $USER:$USER /mnt/build_wrt
@@ -117,6 +116,11 @@ jobs:
 
           $GITHUB_WORKSPACE/Scripts/Settings.sh
           make defconfig -j$(nproc)
+          grep "CONFIG_PACKAGE_init-settings=y" .config
+          if [ $? -ne 0 ]; then
+              echo "Error: init-settings package not enabled in .config!"
+              exit 1
+          fi
 
       - name: Download packages
         run: |
